### ISSUE TITLE
embedded-graphics examples are broken

### ISSUE THREAD

**Issue by rfuest** [jamwaffles/sh1106#10]
The recent upgrade to e-g 0.6 contains a bug in the examples. This:
https://github.com/jamwaffles/sh1106/blob/f945e65f9d0fcb81d91ae99fa36b151724491cb9/examples/graphics.rs#L73-L75
was changed to:
https://github.com/jamwaffles/sh1106/blob/7b38a7c7d5eb4c4682a7438349174887fe30de9e/examples/graphics.rs#L73-L75
But this doesn't set any stroke color and won't show anything.

**Comment by jamwaffles** [comment]
Oh no! Thanks for catching that, I should've checked the PR more carefully.
