### ISSUE TITLE
gpio_cdev way

### ISSUE THREAD

**Issue by ohmyarch** [jamwaffles/sh1106#19]
There are two interface to access gpio pins: sysfs and gpio character device abi. I have tested them both:

device: rpi4, kernel: 4.19, crates: sh1106+linux-embedded-hal
```rust
let dc = Pin::new(24);
dc.export().unwrap();
while !dc.is_exported() {}
dc.set_direction(Direction::Out).unwrap();
dc.set_value(1).unwrap();
```

device: rpi4, kernel: 5.5, crates: sh1106+linux-embedded-hal(git version, with gpio_cdev feature enabled)
```rust
let mut chip = Chip::new("/dev/gpiochip0").unwrap();
let line = chip.get_line(24);
let handle = line.request(LineRequestFlags::OUTPUT, 1, "test").unwrap();
let dc = CdevPin::new(handle).unwrap();
```

The second one does not work.

Other code are exactly the same:
```rust
let mut spi = Spidev::open("/dev/spidev0.0").unwrap();
let options = SpidevOptions::new()
            .bits_per_word(8)
            .max_speed_hz(400_000)
            .mode(SpiModeFlags::SPI_MODE_0)
            .build();
spi.configure(&options).unwrap();

// get dc ...

let cs = sh1106::builder::NoOutputPin::new();
let mut display: GraphicsMode<_> = Builder::new().connect_spi(spi, dc, cs).into();
display.init().unwrap();
display.flush().unwrap();

// draw some text ...
```

I am not sure whether it is a bug or I made some mistakes.

**Comment by jamwaffles** [comment]
I'm afraid I'm not familiar with either of the GPIO interfaces you mentioned so I can't offer much help. Do you have a logic analyser or scope handy? It would be useful to confirm that data is being output on the SPI bus and the DC pin correctly.

**Comment by ohmyarch** [comment]
Unfortunately, I am actually not familiar with (low-level) embedded things.

**Comment by mvirkkunen** [comment]
What if you use the old sysfs method on the newer kernel? It's deprecated but AFAIK it should still work. If it works then, you can at least narrow out the SPI device from being the problem.

Additionally do you have *any* kind of tool to measure voltage? You could write a test program using both methods that just toggles the pin on and off every second, and use something like a multimeter or even just an LED (with a resistor - don't burn your chip!) to see if the correct pin is being toggled.

**Comment by ohmyarch** [comment]
I cannot find anything related to gpio in /sys on newer kernel, most likely only /dev/gpiochip0 can be used.

**Comment by mvirkkunen** [comment]
Things usually don't get removed immediately when they're deprecated. I think it's just a kernel compilation option that's been turned off, but if you've not compiled your own kernel it might be annoying to change.

What about that measurement tool? Got a multimeter? LED and resistor?

To test the SPI bus you could even use a pair of headphones with a normal audio jack and a resistor in series. I used headphones to debug a video signal by listening to the frequency back when I didn't have an oscilloscope, and if you slow down the SPI bus to a very low frequency you should be able to hear it.
