### ISSUE TITLE
Restore the SPI interface

### ISSUE THREAD

**Issue by mvirkkunen** [jamwaffles/sh1106#2]
SH1106 does support a SPI interface and I have a module that exposes SPI by default. It can be reconfigured to I2C with solder bridges, but I'd prefer SPI since I also have other SPI modules. The module works fine if I just revert 9d5266154787813c0687c533e508e41ca5a1b4c2 and fix the few import errors.

It would also be nice if the SPI interface supported a chip select line to allow the bus to be shared, most SPI drivers support that. It's very easy to add to the the existing interface and I could write a PR that adds SPI with a chip select line.

**Comment by jamwaffles** [comment]
I couldn't find any SPI modules in a quick search on Aliexpress so I chose to remove it, my bad. IIRC the datasheet does mention SPI so I should've left it in. 

I'd certainly welcome a PR to re-enable it and add an optional CS line if you can spare the time!
