### ISSUE TITLE
Support 132x64 display size

### ISSUE THREAD

**Issue by mvirkkunen** [jamwaffles/sh1106#3]
The controller's maximum resolution is actually 132x64 instead of 128x64. Currently it's not possible to draw on the right edge of the display. Adding just 32 bytes to the framebuffer size probably wouldn't a huge deal to support this. I can make a PR for this.

Some modules have a 128x64 panel connected so that two columns from the left and right side are not visible (if they only had masked the rightmost 4 columns off instead, everything would work fine...). This can be fixed by the user by just translating everything by two pixels - but a "visible rectangle" configuration to automatically translate and crop the image would be nice.

**Comment by jamwaffles** [comment]
Closed by #6 afaics
