### ISSUE TITLE
The PreChargePeriod/VcomhDeselect commands are incorrect

### ISSUE THREAD

**Issue by mvirkkunen** [jamwaffles/sh1106#7]
While fixing the addressing I went through all the other commands as well to see if they match up with the datasheet and the two commands in the title seem to be incorrect. I honestly don't know what they do, so I didn't touch them, but I can see the values don't correspond with the ones in the datasheet.

**Comment by jamwaffles** [comment]
Was this fixed in #6? Please close if so :+1:

**Comment by mvirkkunen** [comment]
Nope, it wasn't. I don't really know what those commands do, they're probably just being ignored by the controller as unknown commands, but I'm not sure. I'm pretty sure the datasheet doesn't mention them though.

**Comment by jamwaffles** [comment]
They can probably go then. Perhaps I shouldn't have based this crate off the SSD1306 one :sweat_smile:. PRs welcome or I'll check the datasheet cram a commit into master to remove them.

**Comment by bodyweightenergy** [comment]
I got you a PR that fixes this. (https://github.com/jamwaffles/sh1106/pull/23)

**Comment by jamwaffles** [comment]
Closed by #23
